### ISSUE TITLE
What does corrData stands for in function MatchSiftPoints2

### ISSUE THREAD

**Issue by hoding123** [Celebrandil/CudaSift#16]
Hi, 

Function MatchSiftPoints2 is the core code lines relating to the sift matching process.  Typically ,  Given two set of sift descriptors t1, t2. For any sift descriptor, desc_1 for example,  in t1, we find the two  closest  sift descriptor  sfit1, sift2 in t2 under L2 norm, if the ratio of  L2(desc_1, sift1)/L2(desc_1, sift2) is small than delta. sift1 is accepted as a correspondence of desc_1.

I do not under stand the following meaning of the code line bellow in function MatchSiftPoints2.

  const float *pt1 = &siftPoints1[ty*128];
  const float *pt2 = &siftPoints2[tx*128];
  float sum = 0.0f;
  for (int i=0;i<128;i++) {
    int itx = (i + tx)&127; // avoid bank conflicts
    sum += pt1[itx]*pt2[itx];
  }
  if (p1<numPts1)
    corrData[p1*gridDim.y*16 + p2] = (p2<numPts2 ? sum : -1.0f);

Could you give any explanation or the principle that you used in the sift matching process. Much thanks!

**Comment by Celebrandil** [comment]
I'm not computing the L2 distance between SIFT vectors, but the dot product, since it's faster. If the vectors are normalised though, which they are, then the two operations are equivalent.

(A-B)*(A-B) = A^2 - 2AB + B^2 = 1 - 2AB + 1 = 2 - 2AB = 2*(1-AB)

Thus from corrData you may easily compute the L2 distance as L2 = 2(1-corrData), if you need it. Maybe I should add this last step to the code.

**Comment by rayhou0710** [comment]
Hi,
This might be trivial but just want to double check.

dim3 blocks(iDivUp(numPts1,16), iDivUp(numPts2, 16));
  dim3 threads(16, 16); // each block: 1 points x 16 points
  MatchSiftPoints2<<<blocks, threads>>>(sift1, sift2, d_corrData, numPts1, numPts2);

Should the comment in the second line be 16 points * 16 points instead? Thanks!
