### ISSUE TITLE
matching.cu does not compute the L2 norm?

### ISSUE THREAD

**Issue by dagap** [Celebrandil/CudaSift#3]
Is the matching.cu computing the L2 notm? The line:

sum += siftPoint[16_j+tx] \* ptr2[16_j+tx];

seems to be just element by element multiplication of the feature vector. I am not sure how this computes a distance between the two SIFT descriptors?

Additionally, the sums are being dome many times for the same element of the feature vector. As in the setting, tx would range from 0 to 15...

**Comment by Celebrandil** [comment]
Since the SIFT vector is L2 normalised to 1, a dot product is equivalent to a L2 norm.

(A-B)_(A-B)=A_A + B_B - 2_A_B = 2(1-A_B)

I might change normalisation though and have to keep this in mind. I skip the final sqrt() because it's faster and doesn't change the order of matches.

Yes, tx ranges from 0 to 15, but each tx loops over 8 products, which means 128 in total after final summation.
