### ISSUE TITLE
Non-deterministically getting SiftPoint x, y positions outside image boundary?

### ISSUE THREAD

**Issue by danielsuo** [Celebrandil/CudaSift#4]
Hello!

Thanks for the great library. We were using version three and are now trying version four. However, we notice a problem:

Occasionally, when we run the following code, we get SIFT points that live outside our image boundary (e.g., (341, 491) in an image that is (640, 480). We aren't sure why this is happening because we would expect that given identical images, we should get identical SIFT results (barring floating point errors, but 10+ pixels seems large).

For now, we simply throw out such SIFT points, but are curious to know if you've seen this issue before or if you have a hunch as to why it might be happening. We don't believe we're doing anything special, but please let us know if you think we might be doing something wrong!

Many thanks again for the work and any help!
Daniel

```
# gray is a 640x480 grayscale image read from 16bit PNG
gray.convertTo(gray, CV_32FC1);
unsigned int w = gray.cols;
unsigned int h = gray.rows;

InitCuda();
CudaImage cudaImage;
cudaImage.Allocate(w, h, iAlignUp(w, 128), false, NULL, (float*) gray.data);
cudaImage.Download();

ExtractSift(siftData, cudaImage, 5, 0.0f, 3.0f, 0.0f, 1.0f);
```

**Comment by Celebrandil** [comment]
Yes, that is weird. Boundary effects tend to push DoG peaks away from the image boundaries, so most features stay well within the boundaries. The only real change in the behaviour since last version is in the computation of orientations that now should be a bit more accurate. Do you have the image somewhere?

**Comment by danielsuo** [comment]
Agree; we were really surprised when we saw these errors. You can see a sample stream of images [here](https://drive.google.com/folderview?id=0B_10gtxnPV-_Y0Ftb1RYalhhVkE&usp=sharing), but again, the errors show up for different images on different runs. Not sure why that would happen because SIFT should be deterministic.

**Comment by Celebrandil** [comment]
I think I found the problem, but I haven't been able to confirm it on any images. For small images and coarse scales, the height is not necessarily divisible by 4, resulting in FindPointsMulti reading outside image space. It becomes non-deterministic since the content outside the image could be random (old data). It doesn't result in a memory fault though, since memory is allocated in blocks that are larger than those small image sizes. I uploaded a fix that you may test.

**Comment by danielsuo** [comment]
Ah, ok, that would make sense. What do you imagine changed between the
third and fourth versions such that this might present itself? We never had
this problem before and didn't see anything immediately obvious from
looking at the diffs.

Really appreciate your help looking at this! The hacky solution is just to
ignore the SIFT points outside the image space, so by no means is this
urgent on our end.

**Comment by Celebrandil** [comment]
To reduce costly global memory accesses one often uses local shared memory for storage of data commonly used by multiple threads. However, if you consume too much local shared memory the utilization of multiprocessors decreases. The right balance can be hard to find and might change from one generation of GPUs to the next.

To find a local peak spatially and in scale you need 3^3 memory reads in total, but through the use of local shared memory I only used 3 global memory reads in the third version. In the fourth version, however, I got better utilization and speed by instead using 3^2 global memory reads, since I could reduce the amount of local shared memory. 

The error (probably) occurred since I didn't properly check whether I read inside the image for all these reads. The behaviour of the code should be the same though. I hope you managed to get is solved with the updated code.

**Comment by danielsuo** [comment]
Mårten: missed the commit you posted yesterday; I believe it does solve the
issue.

Your change is also in line with what I imagined, so feel good about
closing the issue. Many thanks again!
